spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/electronic_store_userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: users_schema
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: create
